import Head from "next/head"
import { useState } from "react"
import styles from "../styles/Home.module.css"
import Button from "../component/Button"

export default function Home() {
    const [isBoolean, setIsBoolean] = useState(false)

    function handler() {
        console.log("clicked")
        setIsBoolean((currentIsBoolean) => {
            return !currentIsBoolean
        })
        console.log(isBoolean)
    }

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                {isBoolean ? <div className="">Hello</div> : null}
                <Button buttonName="submit" buttonHandler={handler} />
                <Button buttonName="click me" buttonHandler={handler} />
            </div>
        </>
    )
}
